### ISSUE TITLE
Comments on "Debugging C# code with Unity IL2CPP projects running on HoloLens or immersive headsets"

### ISSUE THREAD

**Issue by LocalJoost** [LocalJoost/BlogComments#324]
Original article: https://localjoost.github.io/debugging-c-code-with-unity-il2cpp/

**Comment by medinags** [comment]
Hi first of all thank you for another amazing blog.
I am trying to do debugging with my HoloLens 2 at runtime, but I have not been able to do it. I followed your blog. 
Current Set up: 
- HoloLens 2
- Unity 2019.4.23
- Legacy 
- MRTK 2.7.2

- What I did
I added a break point and a debug message

![image](https://user-images.githubusercontent.com/78471817/154239162-63b4f0ae-0505-473c-b6c0-20c80ea63e9e.png)

I Enabled internet capabilities 
![image](https://user-images.githubusercontent.com/78471817/154239277-3c54c31e-3c3a-4d32-9d8d-f6c5232ee1c8.png)

I built and deployed the application.
![image](https://user-images.githubusercontent.com/78471817/154239494-ce7f4ac4-7fc8-4740-adfc-caa01046532d.png)
![image](https://user-images.githubusercontent.com/78471817/154239556-5c541b65-7a80-4d4e-b5ab-baf0e44a04d5.png)

My device is connected to my PC access point. 
![image](https://user-images.githubusercontent.com/78471817/154239811-caf756b5-a82c-4dc2-8fef-ac9ffa838e88.png)

In the solution when I click on Debug - Attach Unity ... I can see my divice 
![image](https://user-images.githubusercontent.com/78471817/154239858-6f4b9bdc-4d42-4778-a6e8-7cdcd6f2da48.png)

After I select it, it shows me this in VS
![image](https://user-images.githubusercontent.com/78471817/154240375-0e6020c8-0d57-4e6d-ad78-7b31381869d1.png)

But the "AppContainer Network Isolation Diagnostics Tool" does not appear.
Do you know what I could be doing wrong?

**Comment by LocalJoost** [comment]
First of all, thank you for your comprehensive message. I wish everyone took so much trouble as you. The "AppContainer Network Isolation Diagnostics Tool" does not appear anymore, or not in a window at least. I think that stopped with Unity 2019. So I think you are fine. The breakpoints should be hit.  But most likely the Start method is already called after you attach. Could you try placing a breakpoint in something called by Update?

**Comment by medinags** [comment]
I have changed it, when I use speech recognition, it works, but nothing happens in the VSdebug. 

![image](https://user-images.githubusercontent.com/78471817/154244777-381a3270-facd-4d5a-9356-3499515fc43f.png)

![image](https://user-images.githubusercontent.com/78471817/154245520-2d0ee7d3-7a72-49ca-8ec7-9eba539b256d.png)



I found this in microsoft documentation
![image](https://user-images.githubusercontent.com/78471817/154245443-cec90455-1e5b-4987-bd8c-eb3972d6e69d.png)

But I think everything is correct on my PC
![image](https://user-images.githubusercontent.com/78471817/154245201-eacf4cbf-77c9-490d-91e4-a1094b8e6087.png)

**Comment by medinags** [comment]
I think it is working, because when I pause the debugger in VS the application pauses.

![image](https://user-images.githubusercontent.com/78471817/154251601-8042cbfb-7b20-48b3-ba08-bcb6755f70f0.png)

 But, I don't understand how it works. It shows me the MRTK scripts, but I can't find the scripts I created.

**Comment by LocalJoost** [comment]
Okay, try the following:

- Delete the generated C++ solution completely
- Select the option "Wait for Managed Debugger".
- Generate the solution from scratch again from Unity
- Deploy to HoloLens
- Start manually (so NOT from Visual Studio)
- See if the app shows 'waiting for debugger'
- Connect the debugger as you already did
- Check if the app now continues to start up up
- Try to hit the breakpoint 

And tell me what happened

**Comment by medinags** [comment]
I did everything you told me to do, 
The application starts when I enter VS debug mode.
I try to hit the breakpoint but nothing happens. 
I want to clarify something.
The breakpoint must be defined in the script that is in Unity? Because that's what I did.
Another thing, what is supposed to happen when I hit the breakpoint. Should I see the Debug.log() message and the app should stop?

**Comment by LocalJoost** [comment]
Yes. The breakpoint should be defined in the Unity solution, not the generated C++ solution and  you should try to debate the g FROM the Unity solution . It looks like you are connecting to the HoloLens app allright. So why the breakpoint is not hit, I don't know.

The app should run up until the breakpoint, then freeze.

Does the breakpoint stay red in the solution when you debug? , or does it look different? If you hover over rot, does it say something like 'this breakpoint won't be hit'?

**Comment by medinags** [comment]
I'm sorry I didn't understand very well. I was launching the debug from the sln that is generated when I build the APP. And not from the main Unity solution. 
Rookie mistake.
Everything works perfectly now. 
Thanks, and thanks for your time

**Comment by LocalJoost** [comment]
Ah yes. A common misconception. My blog actually said it:
"Go back to your Unity C# ('editor' ) solution"
But people often miss it. It's a convoluted procedure. I am _very_ glad I got you going. Good luck on your HoloLens endeavors and welcome to the wonderful world of HoloLens development :)
