### ISSUE TITLE
App crashes when the HoloLens sees a QR code

### ISSUE THREAD

**Issue by Ryxuu** [LocalJoost/BlogComments#373]
Dear Joost,

I deployed your solution to HoloLens 2. I use the same version of Unity, MRTK and MRTK QR package. Unity loads the project correctly and builds it. I can deploy it with Visual Studio 2019 without errors. When the app starts I give it all the permissions it requires. The Debug logger panel appears and reads "QR tracker initialized" and "Enabled tracking" and if I show a QR code it crashes with the following debug output:

Exception thrown at 0x00007FFCD59CA71C in Networking.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000006CF0EFDAC0.
Exception thrown at 0x00007FFCD59CA71C in Networking.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000006CF0EFF830.
Exception thrown at 0x00007FFCD59CA71C (KernelBase.dll) in Networking.exe: WinRT originate error - 0x80004003 : 'Invalid pointer'.
'Networking.exe' (Win32): Loaded 'C:\Windows\system32\msxml6.dll'. 
Exception thrown at 0x00007FFCD59CA71C in Networking.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0000006CF0EFF920.

What could be the problem? Can you help me?

If you need more info please let me know.

Thank you!

Best,
Abraham

**Comment by LocalJoost** [comment]
Uhm... you closed the comment. Does this mean you solved your issue?

**Comment by Ryxuu** [comment]
Sorry, I accidentally closed it. Re-opened now. I did not solve the issue.

**Comment by LocalJoost** [comment]
Okay. Did you deploy for Master/ARM64?

**Comment by Ryxuu** [comment]
I deployed it as Release/ARM64.

**Comment by LocalJoost** [comment]
Try Master / ARM64

**Comment by Ryxuu** [comment]
Unfortunately it did not help. Now I encountered a new problem. The VS says the deployment was succes. But on HoloLens the app does not appear in the app list. Have you ever experienced this strange behavior?

**Comment by LocalJoost** [comment]
Sometimes. Try to delete is via the device portal. If that fails, reboot the HoloLens and try again. You are SURE you have deployed it to the HoloLens?
Are you running Insiders? Have you encountered other problems when downloading stuff from github while deploying? Do you have internet? Help me a little here. I am just guessing, you see ;)

**Comment by Ryxuu** [comment]
Thank you for your kind help! :-)
In VS I select the Master/ARM64/Device options. How can I be sure it deploys to HoloLens? I did not encounter other problems and I have internet connection. I am not running Insiders.

**Comment by LocalJoost** [comment]
Okay. So I downloaded the code fresh form GitHub, built the app from scratch, deployed it to the HoloLens2, started it, gave the consents it asked for and it worked right the first time.
What I do, after downloading the code, is the following:

- I open the project in Unity and wait for the import to complete
- I hit CTRL+SHIFT+B
- I select "Windows Universal Platform" and 10.0.18362 as miminum platform version
![image](https://user-images.githubusercontent.com/4129183/110459831-bd72cb00-80cd-11eb-9228-36eb45f29ff7.png)
- I then hit BUILD and build the C++ solution
- When that is done, I open the C++ solution is Visual Studio 2019
- I use the following settings:
![image](https://user-images.githubusercontent.com/4129183/110460001-f27f1d80-80cd-11eb-9ea0-5bdbb39b79f0.png)
- I click Build/Deploy Solution
- The app is deployed to the HoloLens2
- I start the app and it works.

Further conditions:
- My HoloLens 2 is set to US/English language (no idea if that might influence stuff)
- I am deploying over USB

This should really get you going. If it does, kindly let me know what step(s) helped you to get over that weird error you get.

**Comment by Ryxuu** [comment]
Thank you! 

I applied exactly the same settings both in Unity Build Settings and in VS2019. I also deploy the app over USB. It still does not work. I checked it on Device Portal and the app is not deployed at all. I do not understand. How can I be sure it deploys to HoloLens?

**Comment by LocalJoost** [comment]
If it deployed correctly, Visual Studio should say this: 
![image](https://user-images.githubusercontent.com/4129183/110471632-a687a500-80dc-11eb-8313-d80e33699793.png)
In the device portal, you then should be able to select Views/Apps and under installed apps QRCodeService (App). 
![image](https://user-images.githubusercontent.com/4129183/110472042-2b72be80-80dd-11eb-8278-ab42a7e76f4c.png)

If that does not work, I have no idea what is going wrong. I suppose you already tried rebooting both HoloLens and your development PC?

**Comment by Ryxuu** [comment]
Thank you for you answer. Yes, I did reboot the hololens and the PC as well. It is interesting, because other UWP projects work fine.

The output of VS2019 is exactly the same as yours. It differs only in the size of copied files. In my case is 97 MB.

**Comment by LocalJoost** [comment]
The number difference is not strange. It's the output from a different project, but the general output should be the same.

I have no idea what is going wrong at your end. Did you try to delete everything (_including the output project_) and built everything again clean from GitHub?

**Comment by Ryxuu** [comment]
Yes I tried it. I noticed if I deploy it an app appears in the list called demo2. I will try to reset back HoloLens 2 to factory settings. Maybe it helps. We will try it on other PC but this behavior is very strange. I have never encountered this kind of error before.

Thanks for your kind help again!

**Comment by LocalJoost** [comment]
All right. I have a crazy idea. I have been having a look through my project and notice the Package name and display name are set to "Template3D". This is the Unity default. What might have happend is that you had some _other_ app on you device that also had the same package name - and my app has been put over it,  but without getting the new description.

So I made a special branch just for you to try this out, in which I changed the package name: 
![image](https://user-images.githubusercontent.com/4129183/110649375-d2c52380-81b9-11eb-8d0a-6a7a6c6938b9.png)
https://github.com/LocalJoost/QRCodeService/tree/PackageNameChange. I would like you to:

- Completely delete the C++ application that has been generated before
- Pull this branch
- Build the app anew and try to deploy. Lets see if it now appears on your HoloLens.

**Comment by Ryxuu** [comment]
Thank you again! :-)

I have reset the HoloLens and it solved the problem. The app deployed, appeard in the list and works. :)
I also thought that the 'Template3D' as package and display name could cause the problem but to reset the device was the easier way. :)

Thank you again for all the help!

**Comment by LocalJoost** [comment]
Aha, awesome. Have fun
